# Generated by Django 3.1.2 on 2020-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neha', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pan_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='sub_tree',
            field=models.ManyToManyField(blank=True, to='Neha.Tree'),
        ),
    ]
